language: node_js
node_js:
- 8.11.1
branches:
  only:
  - source

install: npm install

before_script:
- git config --global user.name "charlieshao5189"
- git config --global user.email "charlieshao5189@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build